kind: ConfigMap
apiVersion: v1
metadata:
  namespace: clients
  name: java-cloud-producer-config
data:
  config.properties: |-
     bootstrap.servers=$(BOOTSTRAP_SERVERS)
     ssl.endpoint.identification.algorithm=https
     security.protocol=SASL_SSL
     sasl.mechanism=PLAIN
     sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=$(API_KEY) password=$(API_TOKEN);
     client.id=chuck-java-producer
     key.serializer=org.apache.kafka.common.serialization.StringSerializer
     value.serializer=org.apache.kafka.common.serialization.StringSerializer