kind: ConfigMap
apiVersion: v1
metadata:
  namespace: clients
  name: kafka-proxy-config
  annotations:
    reloader.stakater.com/match: "true"
data:
  jaas.config: |-
   KafkaServer {
     org.apache.kafka.common.security.plain.PlainLoginModule required
     username="<API-KEY>"
     password="<API_PASSWORD>"
    };
  bootstrap_servers: <BOOTSTRAP_SERVERS>